<template>
  <!-- activity report listing -->
  <div>
    <NavbarBrand />

    <!-- listing -->
    <div class="container pt-5 mt-5 pb-5">
      <h2 class="text-center mb-5">Actifit Telos - Block Producer Code of Conduct</h2>



		<div>
		<div>
		<h4>Vision</h4>
		Actifit kicked off its Telos branch as part of expansion efforts to other blockchains. We are currently running on 3 DPOS blockchains, namely Hive, Steem, and Blurt.
		Actifit as a project has been running since 2018, we believe in open source and open communication. We are committed to providing an excellent experience to our community on Telos as we have on other chains, and to help with Telos growth as we are as strong as our strongest partners.
		We believe we are greatly positioned to expand the user base across all our different blockchains, and particularly Telos, as we provide unique use case by incentivizing and rewarding our users for living healthier and earning rewards for tracking their steps and daily activity.
		</div>
		<div class="pt-4">
		<h4>Block Production</h4>
		As part of support to the different chains we run on top of or we partner with, we do have nodes supporting hive, hive-engine, and blurt chains. We do have years of experience in running servers and block producing nodes, and we are putting our expertise into running our actifit telos node with utmost efficiency, security, and stability, while protecting the interests of Telos project and its community.
		</div>
		<div class="pt-4">
		<h4>Governance</h4>
		Actifit Telos adheres to the Telos governance documents available at https://telos.net, including arbitration,  regproducer, and operating agreements.
		</div>
		<div class="pt-4">
		<h4>Arbitration</h4>
		Actifit supports arbitration actions whenever applies, when making decisions as a telos block producer.
		</div>
		<div class="pt-4">
		<h4>Independence</h4>
		Actifit is funded by the founding team and the revenue generated by Actifit as a project. We do not give finanical or operational control to any investor over actifit telos as a company.
		We strive to remain community-oriented project as we have been across the past years, and always operate with the community's best interest in mind.
		</div>
		
		</div>

	</div>

    <Footer />
    
  </div>
</template>